### ISSUE TITLE
How to use CoherenceMetrics?

### ISSUE THREAD

**Issue by alonsopg** [ricsinaruto/dialog-eval#7]
After reading through the code:

```
  def update_metrics(self, resp_words, gt_words, source_words):
    '''
    Params:
      :resp_words: Response word list.
      :gt_words: Ground truth word list.
      :source_words: Source word list.
    '''
    avg_source = self.avg_embedding(source_words)
    avg_resp = self.avg_embedding(resp_words)

    # Check for zero vectors and compute cosine similarity.
    if np.count_nonzero(avg_resp) and np.count_nonzero(avg_source):
        self.metrics['coherence'].append(
          1 - distance.cosine(avg_source, avg_resp))

```
One could import from the code `update_metrics` function from `CoherenceMetrics`. Although the function receives `resp_words`,  `gt_words`, `source_words`, it is not clear to me how to use the function. Could anybody provide a real example of how to call and use Coherence Metrics?

**Comment by ricsinaruto** [comment]
This function is not designed to be called in a standalone manner since it uses word embeddings initialized in the constructor. It computes the metrics for the inputs and appends it to the self.metrics list. The code is designed to work together.

You would have to heavily modify the code to use the class alone. I advise you to just run the program normally and in the config file specify that only the coherence metric should be computed (see readme).

**Comment by alonsopg** [comment]
Thanks for the help, could you provide an example of how to do it for arbitrary utterances?

**Comment by ricsinaruto** [comment]
I don't really understand what you mean. If you want to run the program everything is in the readme. You need to have source utterances and responses in two separate files.
